class ACCOUNTS_ID {
  static const MAIN_ACCOUNT_ID = 'MAIN';
  static const LEDGER_ACCOUNT_ID = 'LEDGER';
  static const EXPENDITURE_ACCOUNT_ID = 'EXPENDITURE';
  static const SALES_ACCOUNT_ID = 'SALES';
  static const ASSETS_ACCOUNT_ID = 'ASSETS';
  static const BANKS_ACCOUNT_ID = 'BANKS';
  static const NBO_ACCOUNT_ID = 'NBO';
  static const PETTY_CASH_ACCOUNT_ID = 'PETTY_CASH';
  static const CASH_DRAWER_ACCOUNT_ID = 'CASH_DRAWER';
  static const DEBTORS_ACCOUNT_ID = 'DEBTORS';
  static const LIABILITIES_ACCOUNT_ID = 'LIABILITIES';
}

var payerAccounts = [
  // ACCOUNTS_ID.EXPENDITURE_ACCOUNT_ID, // expenditure can not pay for expenditure
  // ACCOUNTS_ID.LEDGER_ACCOUNT_ID,
  ACCOUNTS_ID.CASH_DRAWER_ACCOUNT_ID,
  ACCOUNTS_ID.NBO_ACCOUNT_ID,
  ACCOUNTS_ID.PETTY_CASH_ACCOUNT_ID,
  ACCOUNTS_ID.SALES_ACCOUNT_ID,
  ACCOUNTS_ID.ASSETS_ACCOUNT_ID,
  ACCOUNTS_ID.BANKS_ACCOUNT_ID,
  ACCOUNTS_ID.DEBTORS_ACCOUNT_ID,
  ACCOUNTS_ID.LIABILITIES_ACCOUNT_ID,
];
