import 'package:shop/accounting/account/account_model.dart';

const ACCOUNTS_TREE = const [
  AccountModel(
    id: 'ledger',
    parentId: 'main',
    titleEnglish: 'Ledger Report',
    titleArabic: 'لجر ريبورت',
    titlePersian: 'گزارش گروه های حسابداری',
    note: '',
  ),
  AccountModel(
    id: 'sales',
    parentId: 'ledger',
    titleEnglish: 'Sales',
    titleArabic: 'مبيعات',
    titlePersian: 'فروش',
    note: '',
  ),
  AccountModel(
    id: 'expenditure',
    parentId: 'ledger',
    titleEnglish: 'Expenditure',
    titleArabic: 'مصاريف',
    titlePersian: 'هزینه ها',
    note: '',
  ),
  AccountModel(
    id: 'assets',
    parentId: 'ledger',
    titleEnglish: 'Assets',
    titleArabic: 'اصول',
    titlePersian: 'دارایی ها',
    note: '',
  ),
  AccountModel(
    id: 'banks',
    parentId: 'assets',
    titleEnglish: 'Banks',
    titleArabic: 'بنوك',
    titlePersian: 'بانک ها',
    note: '',
  ),
  AccountModel(
    id: 'nbo',
    parentId: 'banks',
    titleEnglish: 'NBO Bank',
    titleArabic: 'بنک عمان الوطني',
    titlePersian: 'بانک ان بی او',
    note: '',
  ),
  AccountModel(
    id: 'petty-cash',
    parentId: 'assets',
    titleEnglish: 'Petty Cash',
    titleArabic: 'بتي كش',
    titlePersian: 'تن خواه',
    note: '',
  ),
  AccountModel(
    id: 'cash-drawer',
    parentId: 'assets',
    titleEnglish: 'Cash Drawer',
    titleArabic: 'صندوق',
    titlePersian: 'صندوق',
    note: '',
  ),
  AccountModel(
    id: 'debtors',
    parentId: 'assets',
    titleEnglish: 'Debtors',
    titleArabic: 'بنک عمان الوطني',
    titlePersian: 'المدينين',
    note: '',
  ),
  AccountModel(
    id: 'liabilities',
    parentId: 'ledger',
    titleEnglish: 'Liabilities',
    titleArabic: 'بنک عمان الوطني',
    titlePersian: 'الدين الحالي',
    note: '',
  ),
];
